<a href="https://colab.research.google.com/github/Ali-Radi/lab1/blob/main/Copy_of_Python_Numpy_Exercises_with_hints.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python NumPy Exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` and print the numpy version and the configuration (★☆☆)

`Hint: import … as` and `np.__version__, np.show_config)`

In [1]:
import numpy as np

#### 2. Convert a list of numeric value into a one-dimensional NumPy array (★☆☆)
`💡 hint: numpy.array`

In [2]:
my_list = np.array([1, 2, 3, 4, 5])
my_list

array([1, 2, 3, 4, 5])

#### 3. Create a null vector of size 9 (★☆☆)
`💡 hint: np.zeros`

In [3]:
null_list = np.zeros(9)
null_list

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)
`💡 hint: size, itemsize`

In [4]:
null_list.size

9

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
`💡hint: np.info`

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 12 but the sixth value which is 1 (★☆☆)
`💡hint: array[12]`

In [6]:
null_list = np.zeros(12)
null_list[5] = 1
null_list

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 20 to 59 (★☆☆)
`💡hint: arange`

In [7]:
my_vector = np.arange(20, 60)
my_vector

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Reverse a vector (first element becomes last) (★☆☆)
`💡hint: array[::-1]`

In [8]:
my_vector[::-1]

array([59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43,
       42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26,
       25, 24, 23, 22, 21, 20])

#### 9. Create a 3x3 matrix with values ranging from 12 to 20 (★☆☆)
`💡hint: reshape`

In [9]:
mat = np.arange(12, 21).reshape(3, 3)
mat

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Find indices of non-zero elements from [3,7,0,0,9,0] (★☆☆)
`💡hint: np.nonzero`

In [10]:
my_list = np.array([3, 7, 0, 0, 9, 0])
np.nonzero(my_list)

(array([0, 1, 4]),)

#### 11. Create a 4x4 identity matrix (★☆☆)
`💡hint: np.eye`

In [11]:
id_matrix = np.eye(4)
id_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### 12. Create a 2x2x2 array with random values (★☆☆)
`💡hint: np.random.random`

In [12]:
random_array = np.random.random((2, 2,2))
random_array

array([[[0.4608598 , 0.79438243],
        [0.39608143, 0.28919115]],

       [[0.27617985, 0.10334191],
        [0.63468627, 0.48396687]]])

#### 13. Create a 9x9 array with random values and find the minimum and maximum values (★☆☆)
`💡hint: min, max`

In [13]:
random_array = np.random.random((9, 9))
print(random_array)
print(random_array.min())
print(random_array.max())

[[0.94994196 0.46965846 0.1602587  0.33093112 0.17419797 0.39351277
  0.25720618 0.37470001 0.12966595]
 [0.23638415 0.63790169 0.96029419 0.6974289  0.62592906 0.73729334
  0.55715907 0.18194653 0.74566491]
 [0.41347159 0.35738825 0.28091514 0.42030312 0.05059334 0.22543699
  0.08659046 0.76686821 0.93711312]
 [0.94124849 0.81650983 0.29859698 0.06439059 0.96720312 0.31537707
  0.95272439 0.71459756 0.12166048]
 [0.29342405 0.97029797 0.15388523 0.23682605 0.90507841 0.13693922
  0.01628666 0.35082732 0.13708907]
 [0.54501104 0.01488146 0.10576558 0.47855323 0.53537832 0.44575202
  0.77006898 0.30488085 0.08920611]
 [0.56547375 0.73464411 0.67413206 0.45133682 0.52175486 0.07512154
  0.91952262 0.52919752 0.32468861]
 [0.97964916 0.8381465  0.57229624 0.42574997 0.56320728 0.91803194
  0.95711621 0.94930172 0.12541942]
 [0.28704605 0.23273037 0.37404036 0.33763527 0.02761417 0.07980975
  0.45330677 0.55365516 0.0125959 ]]
0.012595897503770548
0.9796491570946183


#### 14. Create a random vector of size 20 and find the mean value (★☆☆)
`💡hint: mean`

In [14]:
random_vector = np.random.random(20)
print(random_vector)
print(random_vector.mean())

[0.74395581 0.45700267 0.31714927 0.81807287 0.96875441 0.5098099
 0.76926498 0.36822407 0.1420731  0.27379623 0.17392423 0.98599705
 0.92301928 0.96606927 0.95521192 0.96880846 0.10780901 0.57047353
 0.77679024 0.63981468]
0.6218010484476792


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
`💡hint: array[1:-1, 1:-1]`

In [15]:
d2array = np.ones((5, 5))
d2array[1:-1, 1:-1] = 0
d2array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
`💡hint: np.pad`

In [16]:
d2array = np.zeros((5, 5))
d2array[1:-1, 1:-1] = 1
d2array

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```
`💡hint: NaN = not a number, inf = infinity`

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.7 == 7 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 6x6 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`💡hint: np.diag`

In [18]:
nmatrix = np.diag([1, 2, 3, 4],k=-1)
nmatrix

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 6x6 matrix and fill it with a checkerboard pattern (★☆☆)
`💡hint: array[::2]`

In [19]:
my_matrix = np.zeros((6, 6), dtype=int)
my_matrix[1::2, ::2] = 1
my_matrix[::2, 1::2] = 1
my_matrix

array([[0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0]])

#### 20. Consider a (8,9,10) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
`💡hint: np.unravel_index`

In [20]:
arr = np.random.random((8, 9, 10))
print(np.unravel_index(100, arr.shape))

(np.int64(1), np.int64(1), np.int64(0))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
`💡hint: np.tile`

In [21]:
np.tile(np.array([[0, 1], [1, 0]]), (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 6x6 random matrix (★☆☆)
`💡hint: (x -mean)/std`

In [22]:
nmatrix = np.random.random((6, 6))
nmatrix = (nmatrix - np.mean(nmatrix)) / np.std(nmatrix)
nmatrix

array([[ 1.13170346, -1.3190774 ,  0.83597798, -0.94179257, -0.08870858,
         0.12384253],
       [ 0.89317708, -1.08753594,  1.0117448 ,  0.09535938, -0.73645547,
        -0.28194183],
       [ 1.05354998, -0.29533974,  0.77791345,  1.01219287,  0.0357784 ,
        -1.7104295 ],
       [ 1.12984054,  0.41919275, -0.58359426,  1.29022861,  1.92706959,
        -1.56699183],
       [-0.00571444, -0.4571917 , -1.34989883,  0.1915261 , -0.59359304,
         0.193826  ],
       [-1.69338987, -0.33172529, -0.61261451, -1.44435078,  1.37606313,
         1.60135892]])

#### 23. find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. (★☆☆)

In [23]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.size)
print(arr.itemsize)
print(arr.nbytes)

5
8
40


#### 24. Multiply a 6x3 matrix by a 3x4 matrix (real matrix product) (★☆☆)
`💡hint: np.dot` or `np.ones`

In [24]:
matrix1 = np.random.random((6, 3))
matrix2 = np.random.random((3, 4))
np.dot(matrix1, matrix2)

array([[0.56492701, 0.7402092 , 0.73309323, 0.56659846],
       [0.78243872, 0.95828537, 0.97863877, 1.06825849],
       [0.47101779, 0.61944313, 0.64970458, 0.68981368],
       [0.8665154 , 0.74358055, 0.64063096, 0.88860068],
       [0.76943813, 1.15745159, 1.21038288, 0.9323736 ],
       [0.44972661, 0.84499153, 0.93209858, 0.63778292]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
`💡hint: >, <`

In [25]:
arr = np.arange(10)
arr[(arr > 3) & (arr < 8)] *= -1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆)
```python

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Write a Python program compare two arrays using numpy (★☆☆)
```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [27]:
arr1 = np.array([1, 2])
arr2 = np.array([4, 5])
print(np.array_equal(arr1, arr2))
print(arr1 > arr2)
print(arr1 >= arr2)
print(arr1 < arr2)
print(arr1 <= arr2)

False
[False False]
[False False]
[ True  True]
[ True  True]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```
Consider an integer vector a
```python
a**a
a << a >> 2
a <- a
1j*a
a/1/1
a<a>a
```

In [32]:

np.array(0) / np.array(0)  # NaN
np.array(0) // np.array(0)  # 0
np.array([np.nan]).astype(int).astype(float)


/tmp/ipython-input-3145585231.py:13: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)
`💡hint: np.uniform, np.copysign, np.ceil, np.abs, np.where`

In [33]:
arr = np.random.uniform(-10, +10, 10)
print(arr)
print(np.copysign(np.ceil(np.abs(arr)), arr))

[ 9.87308664  2.33729372 -5.12861535 -0.28847952  2.20550138  9.57693147
  6.71421408 -2.25809287  6.74650642  4.99304583]
[10.  3. -6. -1.  3. 10.  7. -3.  7.  5.]


#### 30. How to find common values between two arrays? (★☆☆)
`💡hint: np.intersect1d`

In [34]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])
np.intersect1d(arr1, arr2)

array([3, 4, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
`💡hint: np.seterr, np.errstate`

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```
`💡hint: imaginary number`

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
`💡hint: np.datetime64, np.timedelta64`

#### 34. How to get all the dates corresponding to the month of January 2016? (★★☆)
`💡hint: np.arange(dtype=datetime64['D'])`

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
`💡hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=)`

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
`💡hint: %, np.floor, astype, np.trunc`

#### 37. Create a 3x3 matrix with row values ranging from 0 to 2 (★★☆)
`💡hint: np.arange`

#### 38. Consider a generator function that generates 9 integers and use it to build an array (★☆☆)
`💡hint: np.fromiter`

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
`💡hint: np.linspace`

#### 40. Create a random vector of size 10 and sort it (★★☆)
`💡hint: sort`

#### 41. How to sum a small array faster than np.sum? (★★☆)
`💡hint: np.add.reduce`

#### 42. Consider two random array A and B, check if they are equal (★★☆)
`💡hint: np.allclose, np.array_equal`

#### 43. Make an array immutable (read-only) (★★☆)
`💡hint: flags.writeable`

#### 44. Consider a random 5x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
`💡hint: np.sqrt, np.arctan2`

#### 45. Create random vector of size 5 and replace the maximum value by 0 (★★☆)
`💡hint: argmax`

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
`💡hint: np.meshgrid`

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
`💡hint: np.subtract.outer`

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
`💡hint: np.iinfo, np.finfo, eps`

#### 49. How to print all the values of an array? (★★☆)
`💡hint: np.set_printoptions`

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
`💡hint: argmin`

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
`💡hint: dtype`

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
`💡hint: np.atleast_2d, T, np.sqrt`

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
`💡hint: view and [:] =`

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```
`💡hint: np.genfromtxt`

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
`💡hint: np.ndenumerate, np.ndindex`

#### 56. Generate a generic 2D Gaussian-like array (★★☆)
`💡hint: np.meshgrid, np.exp`

#### 57. How to randomly place e elements in a 2D array? (★★☆)
`💡hint: np.put, np.random.choice`

#### 58. Subtract the mean of each row of a matrix (★★☆)
`💡hint: mean(axis=,keepdims=)`

#### 59. How to sort an array by the nth column? (★★☆)
`💡hint: argsort`

#### 60. How to tell if a given 2D array has null columns? (★★☆)
`💡hint: any, ~`

#### 61. Find the nearest value from a given value in an array (★★☆)
`💡hint: np.abs, argmin, flat`

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
`💡

#### 63. Create an array class that has a name attribute (★★☆)
`💡hint: class method`

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
`💡hint: np.bincount | np.add.at`

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
`💡hint: np.bincount`

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
`💡hint: np.unique`

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
`💡hint: sum(axis=(-2,-1))`

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)
`💡hint: np.bincount`

#### 69. How to get the diagonal of a dot product? (★★★)
`💡hint: np.diag`

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
`💡hint: array[::4]`

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
`💡hint: array[:, :, None]`

#### 72. How to swap two rows of an array? (★★★)
`💡hint: array[[]] = array[[]]`

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)
`💡hint: repeat, np.roll, np.sort, view, np.unique`

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
`💡hint: np.repeat`

#### 75. How to compute averages using a sliding window over an array? (★★★)
`💡hint: np.cumsum`

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
`💡hint: from numpy.lib import stride_tricks`

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
`💡hint: np.logical_not, np.negative`

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)
`💡hint: minimum maximum`

#### 81. Consider an array a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
`💡hint: stride_tricks.as_strided`

#### 82. Compute a matrix rank (★★★)
`💡hint: np.linalg.svd`

#### 83. How to find the most frequent value in an array?
`💡hint: np.bincount, argmax`

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
`💡hint: stride_tricks.as_strided`

#### 85. Create a 2D array subclass such that a[i,j] == a[j,i] (★★★)
`💡hint: class method`

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
`💡hint: np.tensordot`

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
`💡hint: np.add.reduceat`

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)
`💡hint: np.argsort | np.argpartition`

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
`💡hint: np.indices`

#### 91. How to create a record array from a regular array? (★★★)
`💡hint: np.core.records.fromarrays`

#### 92. Consider a large vector A, compute A to the power of 3 using 3 different methods (★★★)
`💡hint: np.power, *, np.einsum`

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
`💡hint: np.where`

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)
`💡hint: np.unpackbits`

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)
`💡hint: np.ascontiguousarray | np.unique`

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
`💡hint: np.einsum`

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
`💡hint: np.cumsum, np.interp`

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
`💡hint: np.logical_and.reduce, np.mod`

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
`💡hint: np.percentile`